TP02Module05_Partie_2/Controllers/PizzaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;


namespace TP02Module05_Partie_2.Controllers
{
    public class PizzaController : Controller
    {
        private static List<Pizza> pizzas = new List<Pizza>();
        private static List<Ingredient> ingredients = Pizza.IngredientsDisponibles;
        private static List<Pate> pates = Pizza.PatesDisponibles;

        // GET: Pizza
        public ActionResult Index()
        {
            return View(pizzas);
        }

        // GET: Pizza/Details/5
        public ActionResult Details(int id)
        {
            Pizza pizza = getPizzaById(id);
            if(pizza == null)
            {
                return RedirectToAction("Index");
            }
            return View(pizza);
        }

        // GET: Pizza/Create
        public ActionResult Create()
        {
            var pizzaVM = new CreateEditPizzaVM { Ingredients = ingredients, Pates = pates };
            return View(pizzaVM);
        }

        // POST: Pizza/Create
        [HttpPost]
        public ActionResult Create(CreateEditPizzaVM pizzaVM)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (validatePizza(pizzaVM))
                    {
                        Pizza pizza = new Pizza
                        {
                            Id = pizzas.OrderByDescending(p => p.Id).Select(p => p.Id).FirstOrDefault() + 1,
                            Pate = pates.First(p => p.Id == pizzaVM.IdSelectedPate),
                            Nom = pizzaVM.Pizza.Nom
                        };
                        foreach (var idIngredient in pizzaVM.IdSelectedIngredients)
                        {
                            pizza.Ingredients.Add(ingredients.First(i => i.Id == idIngredient));
                        }

                        pizzas.Add(pizza);

                        return RedirectToAction("Index");
                    }
                }
                pizzaVM.Ingredients = ingredients;
                pizzaVM.Pates = pates;
                return View(pizzaVM);
            }
            catch
            {
                return View();
            }
        }

        // GET: Pizza/Edit/5
        public ActionResult Edit(int id)
        {
            Pizza pizza = getPizzaById(id);

            if(pizza != null)
            {
                var pizzaVM = new CreateEditPizzaVM 
                {
                    Pizza = pizza, 
                    Ingredients = ingredients, 
                    Pates = pates, 
                    IdSelectedIngredients = pizza.Ingredients.Select(i => i.Id).ToList(), 
                    IdSelectedPate = pizza.Pate.Id 
                };
                return View(pizzaVM);
            }
            return View("Index");
        }

        // POST: Pizza/Edit/5
        [HttpPost]
        public ActionResult Edit(CreateEditPizzaVM pizzaVM)
        {
            try
            {
                Pizza pizza = pizzas.SingleOrDefault(p => p.Id == pizzaVM.Pizza.Id);
                if (ModelState.IsValid)
                {
                    if(validatePizza(pizzaVM))
                    {
                        pizza.Nom = pizzaVM.Pizza.Nom;
                        pizza.Ingredients.Clear();
                        foreach (var idIngredient in pizzaVM.IdSelectedIngredients)
                        {
                            pizza.Ingredients.Add(ingredients.First(i => i.Id == idIngredient));
                        }
                        pizza.Pate = pates.First(p => p.Id == pizzaVM.IdSelectedPate);

                        return RedirectToAction("Index");
                    }
                    pizzaVM.Ingredients = ingredients;
                    pizzaVM.Pates = pates;
                    return View(pizzaVM);
                }
                pizzaVM.Ingredients = ingredients;
                pizzaVM.Pates = pates;
                return View(pizzaVM);
            }
            catch
            {
                return View();
            }
        }

        // GET: Pizza/Delete/5
        public ActionResult Delete(int id)
        {
            Pizza pizza = getPizzaById(id);
            if(pizza == null)
            {
                return RedirectToAction("Index");
            }
            return View(pizza);
        }

        // POST: Pizza/Delete/5
        [HttpPost]
        public ActionResult Delete(Pizza pizza)
        {
            try
            {
                pizzas.Remove(pizzas.FirstOrDefault(p => p.Id == pizza.Id));

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // METHODES PRIVEES
        private Pizza getPizzaById(int id)
        {
            var pizza = pizzas.FirstOrDefault(c => c.Id == id);

            return pizza;
        }
        private bool validatePizza(CreateEditPizzaVM pizzaVM)
        {
            bool noError = true;
            if (pizzas.Any(p => p.Nom == pizzaVM.Pizza.Nom && p.Id != pizzaVM.Pizza.Id))
            {
                ModelState.AddModelError("pizzaNom", "Il existe déjà une pizza portant ce nom");
                noError = false;
            }
            if (pizzaVM.IdSelectedIngredients.Count() < 2 || pizzaVM.IdSelectedIngredients.Count() > 5)
            {
                ModelState.AddModelError("pizzaNbIngredients", "Une pizza doit avoir entre 2 et 5 ingrédients");
                noError = false;
            }
            foreach (var pizza in pizzas)
            {
                if(pizza.Id != pizzaVM.Pizza.Id && pizza.Ingredients.Select(p => p.Id).SequenceEqual(pizzaVM.IdSelectedIngredients))
                {
                    ModelState.AddModelError("pizzaMemeIngredients", "Une pizza avec les mêmes ingrédients existe déjà");
                    noError = false;
                }
            }
            return noError;
        }
    }
}

TP02Module05_Partie_2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mon application ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nom de l'application", "Index", "Pizza", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Accueil", "Index", "Pizza")</li>
                    <li>@Html.ActionLink("Pizzas", "Index", "Pizza")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mon application ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>